spring.application.name=CursoJpa
#Conexión básica a la base de datos.
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/cursos?seSSL=false&serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=Dabson12