spring.application.name=PruebaJPA

#Conectarse con Hibernate, de que forma, en este caso
#actualizar lo ya existente en la base de datos, no borrara todo
spring.jpa.hibernate.ddl-auto=update
#Ubicación y datos específicos de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/spring_jpa?seSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dabson12
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect